from pathlib import Path
import json,statistics
p=Path('benchmarks/results/20260912_comparison')
d=json.loads((p/'comparison_data.json').read_text(encoding='utf-8'))
b=d['balanced'];g=d['deep']; bs=b['reviewed'];gs=g['reviewed']
def frac(s,k):
 v=s['scores'][k];return f"{v['passed']}/{v['evaluated']} ({v['percent']:.1f}%)"
def metric(s,k,stat='mean'):return s['performance'][k][stat]
lines=['# Local AI Gateway benchmark comparison','', 'Completed 2026-09-12 on the local Windows Legion. All candidate inference used the existing localhost gateway.','',
'## Recommendation','',
'Prefer the existing **quality=deep (openai/gpt-oss-20b, MXFP4, medium reasoning)** for the tested text workloads: extraction, summaries, small coding tasks, and reasoning. It gave better format compliance and completed this suite in about half Gemma\'s request time. Its slower token generation and longer cold load did not translate into slower completed answers, because it used much less reasoning. The results do not support reserving deep only for rare difficult questions.','',
'Keep **quality=balanced (google/gemma-4-12b-qat, Q4_0, default reasoning on)** as an available alternative, especially when its shorter cold startup matters. This run does not establish a quality or warm-latency advantage for it. No routing mappings were changed. No fast model or alternate reasoning setting was benchmarked, so no fast-tier recommendation is made.','',
'## Main results','', '| Measure | Balanced: Gemma | Deep: GPT-OSS |','|---|---:|---:|']
for label,k in [('Reviewed semantic correctness','semantic_correct'),('Canonical output/schema/format','format_correct'),('Reviewed instruction following','instruction_following')]:lines.append(f'| {label} | {frac(bs,k)} | {frac(gs,k)} |')
lines += [f"| Automatic semantics, before review | {frac(b['automatic'],'semantic_correct')} | {frac(g['automatic'],'semantic_correct')} |",
 f"| Automatic instruction following | {frac(b['automatic'],'instruction_following')} | {frac(g['automatic'],'instruction_following')} |",
'| Code cases / execution tests | 4/4; 13/13 | 4/4; 13/13 |','| Summary semantic passes | 3/4 | 4/4 |','| Summary rubric concepts covered | 15/18 | 18/18 |',
'| HTTP/model request errors | 0/40 | 0/40 |','| Empty final answers / token-budget hits | 1 / 1 | 0 / 0 |',
 f"| Automatic manual queue / reviewed cases | {b['automatic']['manual_review']} / {bs['reviewed_cases']} | {g['automatic']['manual_review']} / {gs['reviewed_cases']} |",'| Reviews still pending | 0 | 0 |','',
'Automatic semantic denominators exclude unknown/manual grades; reviewed semantics include all 40 cases, including empty answers. Canonical format means the existing benchmark representation, which is sometimes stricter than the prompt. Reviewed instruction following passes Gemma summary_004 because it has the requested four bullets; its introduction was not forbidden. It also differs from automatic scoring for deep extract_003: its bare JSON uses the field names in the prompt, which did not mandate the benchmark\'s shorter canonical keys. Semantic correctness in the instruction_following category measures answer content; it is distinct from the overall instruction dimension.','',
'## Latency, throughput, and tokens','', '| Measure | Gemma | GPT-OSS |','|---|---:|---:|']
for label,key,stat,fmt in [('Mean request latency (s)','wall_time_seconds','mean','.3f'),('Median request latency (s)','wall_time_seconds','median','.3f'),('Sum of request time (s)','wall_time_seconds','total','.3f'),('Mean generated tokens/s','tokens_per_second','mean','.2f'),('Median generated tokens/s','tokens_per_second','median','.2f'),('Mean first-token latency (s)','time_to_first_token_seconds','mean','.3f'),('Median first-token latency (s)','time_to_first_token_seconds','median','.3f'),('Cold model load (s; one observation)','model_load_time_seconds','mean','.3f'),('Input tokens','input_tokens','total',',.0f'),('Output tokens, including reasoning','output_tokens','total',',.0f'),('Reasoning output tokens','reasoning_output_tokens','total',',.0f')]:
 lines.append(f'| {label} | {format(metric(bs,key,stat),fmt)} | {format(metric(gs,key,stat),fmt)} |')
for label,fn in [('Combined input + output tokens',lambda s:metric(s,'input_tokens','total')+metric(s,'output_tokens','total')),('Output less reasoning tokens (derived)',lambda s:metric(s,'output_tokens','total')-metric(s,'reasoning_output_tokens','total'))]:lines.append(f'| {label} | {fn(bs):,} | {fn(gs):,} |')
reduction=100*(1-metric(gs,'wall_time_seconds')/metric(bs,'wall_time_seconds'))
lines += ['',f'GPT-OSS used **{reduction:.1f}% less request time** across this suite. Request latency includes gateway/provider work and cold load on the first case; it excludes local grading and report writing. Sum of request time is not total elapsed task time. Both models started each full run unloaded. The initial diagnostic Gemma pilot also observed an 8.812-second load; the table uses the full-run load for both models. Load is from storage/OS cache state as found, not a controlled cold-disk benchmark.','',
'First-token latency is the provider\'s first generated token, which can be reasoning; it is not time to the first final-answer token. Output tokens and tokens/sec include reasoning. Tokenizers differ, so counts are not a shared unit of semantic work. Values are observed for all 40 requests except load time (one each). No time-to-first-final-answer metric was available.','',
'## Semantic correctness by category','', '| Category | Cases | Gemma | GPT-OSS | Gemma mean latency (s) | GPT-OSS mean latency (s) |','|---|---:|---:|---:|---:|---:|']
for cat,s in bs['by_category'].items():
 t=gs['by_category'][cat];lines.append(f"| {cat} | {s['total_cases']} | {frac(s,'semantic_correct')} | {frac(t,'semantic_correct')} | {metric(s,'wall_time_seconds'):.2f} | {metric(t,'wall_time_seconds'):.2f} |")
lines+=['','Per-category format and instruction scores are in each reviewed_summary.json and comparison_data.json.','',
'## Failures, ambiguities, and review decisions','',
'- **classify_004, both models:** returned announcement; expected irrelevant. The prompt calls the text a cafeteria notice but does not define academic relevance. Original expected answer and scored failure retained. Excluding this disputed case gives Gemma 38/39 (97.4%) and GPT-OSS 39/39 (100%); the relative conclusion is unchanged.',
'- **summary_002, Gemma:** consumed all 4,096 output tokens (4,093 reported reasoning tokens) and returned an empty final message after 89.216 seconds. This is a failed delivered answer, despite HTTP success. No expected answer or budget was adjusted after the full run.',
'- **long_001, both:** the prose root cause correctly describes a nonexistent model identifier. Reviewed semantic passes; Gemma still fails JSON-only formatting because of its fence.',
'- **long_002, Gemma:** all four deadlines are right, in combined date-time strings. Nested objects were not prescribed. Reviewed semantic pass; benchmark schema and Markdown-fence failures retained.',
'- **project_005, both:** chemistry lecture is an accurate specialization of lecture; no restricted event_type vocabulary was specified. Reviewed semantic passes.',
'- **reason_004, GPT-OSS:** O(n²) is mathematically correct but differs from the permitted literal O(n^2). Reviewed semantic pass, exact-format/instruction failure.',
'- **extract_003, GPT-OSS:** requested facts in bare JSON with literal prompt field names; semantic and reviewed instruction passes, canonical schema failure.',
'- Gemma repeatedly fences JSON. GPT-OSS also does so in several cases. Neither model achieved universal strict format compliance. Gemma summary_004 uses four bullets plus an introduction, failing the existing canonical bullet-only format check; reviewed explicit instruction compliance passes because an introduction is not forbidden. All its rubric concepts are covered.','',
'Automatic grades remain untouched in raw_results.json, summary.json, results.csv and the original report section. Manual review records explain every adjudication in newly created runs. reviewed_results.json retains automatic_grade when changed; reviewed_summary.json and reviewed_results.csv carry the final scores. All eight summary reviews use the pre-existing concepts and constraints, not keyword-based semantic grading.','',
'## Summary rubric review','', '| Model | Case | Concept coverage | Semantic pass | Mechanical format | Justification |','|---|---|---:|---|---|---|']
for tier,x in d.items():
 for r in x['rows']:
  if r['category']=='summarization':
   v=r['review'];lines.append(f"| {tier} | {r['id']} | {v['coverage_score']}/{v['coverage_max']} | {v['semantic_correct']} | {r['grade']['format_correct']} | {v['notes']} |")
lines += ['','## Protocol and hardware','',
'- Windows Legion model 83LU; NVIDIA RTX 5070 Ti Laptop GPU, 12,227 MiB reported VRAM; 33,752,997,888 bytes physical RAM; NVIDIA driver 616.92.',
'- LM Studio and gateway were already running on 127.0.0.1:1234 and 127.0.0.1:4812. Authenticated model inventory confirmed both exact model IDs and quantizations were installed. No download or model substitution was needed.',
'- Both full runs used all 40 case IDs in identical order, temperature 0.0, 16,384 context, and 4,096 total output tokens per request. Gemma reasoning was its LM Studio default on; GPT-OSS used the configured medium setting. This compares the configured tiers, not equal reasoning algorithms.',
'- Requests were strictly sequential; Gemma completed before GPT-OSS began. Models were unloaded between full runs. Generated code ran only for four curated Python cases using the pre-existing temporary-directory, python -I, five-second mechanism.',
'- Device-wide GPU memory snapshots during inference were 10,755 MiB for Gemma and 10,453 MiB for GPT-OSS. They include desktop/other allocations, are not peaks or model-only measurements, and do not establish RAM/offload costs. Both models ran successfully within the current setup.',
'- No OpenAI API or Codex inference was used as a candidate backend or grading API. Codex performed recorded rubric/adjudication review in this task. No service was exposed beyond localhost.',
'- This is one sequential run per model, plus Gemma pilots. It is a small, curated suite, not statistical evidence of broad superiority. The longer-context cases are short logs/documents and do not test the 16K context limit. Vision, real tool use, long-form coding, heavy concurrent load, and alternate reasoning settings were not benchmarked.','',
'## Inspection, fixes, and validation','',
'All 40 cases parse with unique IDs. reason_002 was independently enumerated and uniquely yields Monday=A, Tuesday=B, Wednesday=D, Thursday=C. project_005 and long_002 explicitly state 2026. long_004 defines alphabetical tie-breaking; its source values independently sum to 1,867,000 ms with eight completed listens. These four prompt fixes were already present.','',
'The first live pilot reproduced all five incomplete outputs at the original 256/384 token caps. Inspection found that app/lmstudio.py had its message-type filter commented out and was returning reasoning as answer text. The filter was restored, and reasoning_output_tokens was added through provider, response schema, endpoint and benchmark reporting. No routing, reasoning setting, auth or bind-address changes were made. The gateway was restarted locally with the existing environment. Original app files were backed up under benchmarks/backups/pre_execution_20260912.','',
'The runner gained optional --max-output-tokens and source SHA-256 records. Original CLI calls still work and retain the original per-case budgets when the override is omitted. After a corrected pilot exposed an enabled/disabled versus boolean mismatch, a narrow enabled_state rule was added only to extract_005 authentication/cors, keeping strict schema types. long_001 unmatched root-cause prose was routed to review. All 40 prompt texts, expected values and curated test expressions remained unchanged.','',
'Validation passed 15 benchmark regression tests plus a provider-response regression with separate reasoning, message and tool-call items. The suite tests cover controlled normalization, wrong values, ambiguous prose, schema separation, unique IDs, code execution, sequential requests, checkpointing and interruption. The final artifact check confirms identical full-run requests except quality, all 95 live requests preserved, all required outputs, complete reviews, and matching frozen suite hashes.','',
'## Runs and saved artifacts','',
'Project report: C:\\Projects\\local-ai-gateway\\benchmarks\\results\\20260912_comparison\\comparison_report.md','',
'All prior results remain untouched. New run folders:','', '| Run | Requests | Folder |','|---|---:|---|']
for pattern,label,n in [('*pilot-initial*','Initial Gemma diagnostic',5),('*pilot-corrected*','Gateway/budget correction pilot',5),('*pilot-validated*','Validated grading pilot',5),('*gemma-full-validated*','Gemma full comparison',40),('*gptoss-full-validated*','GPT-OSS full comparison',40)]:
 folder=next(Path('benchmarks/results').glob(pattern));lines.append(f'| {label} | {n} | `{folder.name}` |')
lines += ['','Each run contains raw_results.json, summary.json, results.csv, manual_review.json and report.md. Both full runs additionally contain reviewed_results.json, reviewed_summary.json, reviewed_results.csv and reviewed_report.md. The comparison folder contains environment/runtime snapshots, execution_audit.json, the frozen review_policy.md, protocol_snapshot, comparison_data.json and this report.','',
'Commands used for the final protocol:','', '```powershell',
'python benchmarks\\run_benchmarks.py --quality balanced --category structured_extraction --max-output-tokens 4096 --name gemma-extraction-pilot-validated',
'python benchmarks\\run_benchmarks.py --quality balanced --max-output-tokens 4096 --name gemma-full-validated',
'python benchmarks\\run_benchmarks.py --quality deep --max-output-tokens 4096 --name gptoss-full-validated', '```','',
'## Remaining benchmark limitations','',
'The cafeteria classification needs a future, predeclared relevance definition. Several extraction prompts leave key names, nested layout or value vocabularies unspecified while the canonical schema is strict; those differences required transparent review in this audit. Future suite revisions should declare required schema and label vocabulary up front, then be benchmarked as a new version. Do not compare the original tiny-budget runs as though they used this protocol. The standard CLI does not automatically apply manual reviews.','',
'LM Studio response semantics and management endpoints were checked against its [chat API documentation](https://lmstudio.ai/docs/developer/rest/chat) and [unload documentation](https://lmstudio.ai/docs/developer/rest/unload). These document separate reasoning/message output items, reasoning usage, and optional load timing. All model-comparison claims above come from saved local measurements.','']
(p/'comparison_report.md').write_text('\n'.join(lines),encoding='utf-8')
for tier,x in d.items():
 run=p.parent/x['run'];s=x['reviewed']
 body=[f'# Reviewed {tier} benchmark','',f'Model: {s["models"][0]}','',f'Semantic: {frac(s,"semantic_correct")}; format: {frac(s,"format_correct")}; instructions: {frac(s,"instruction_following")}.','',f'Reviewed cases: {s["reviewed_cases"]}; pending: 0; errors: {s["errors"]}.','', 'See manual_review.json for justifications, reviewed_summary.json for category and performance metrics, and ../20260912_comparison/comparison_report.md for the comparison.','']
 (run/'reviewed_report.md').write_text('\n'.join(body),encoding='utf-8')
 report=run/'report.md';text=report.read_text(encoding='utf-8').split('\n## Completed review')[0];text+='\n## Completed review\n\nThe table above preserves automatic grading. Final reviewed scores and completed justifications are in reviewed_report.md, reviewed_summary.json, reviewed_results.csv, and manual_review.json.\n';report.write_text(text,encoding='utf-8')
print(p/'comparison_report.md')
